enut_dir: results
metric_best: mae
metric_agg: argmin
tensorboard_each_run: True  # Log to Tensorboard each run
accelerator: "cuda:0"
mlflow:
  use: False
  project: Rebbutal-PE
  name: zinc-RWSE+SPD-CKGConvMLP-BN-BS32
wandb:
  use: False
  project: ZINC
dataset:
  format: PyG-ZINC
  name: subset
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode
  node_encoder_num_types: 21 # actually 21 in Zinc-12k, 28 in Zinc-full
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 4
  edge_encoder_bn: False
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1, 21)
posenc_SPD:
  enable: True
  ksteps: 21
  add_identity: True
  add_node_attr: False
  add_uniform: False
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  enable_ckpt: True  # Checkpointing can now be disabled to save I/O when e.g. just benchmarking.
  ckpt_best: True  # WARNING: Checkpoint every epoch a better model is found may increase I/O significantly.
  ckpt_clean: True # Delete old ckpt each time.
model:
  type: CKGConvNet
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: add
gt:
  stem:
    node_stem: 'rwse_stem'
    edge_stem: 'spd_stem'
    kernel_expected: True
    raw_norm: True
    post_norm: True
    affine_transform: True
    affine_alpha: 0.1
    num_layers: 0
    batch_norm: True
    act: 'gelu'
    ffn_ratio: 2
  layer_type: CKGraphConvMLP
  layers: 10
  n_heads: 64
  dim_hidden: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  layer_norm: False
  batch_norm: True
  dropout: 0.
  attn_dropout: 0.5
  attn:
    mlp_dropout: 0.1
    full_attn: True
    value_proj: False
    out_proj: True
    average: True # no need; force to be
    n_mlp_blocks: 2
    ffn_ratio: 1.
    batch_norm: True
    layer_norm: False
    deg_scaler: True
    clamp: None
    act: 'gelu'
gnn: # decoder --> san_graph = MLP + pooling
  head: san_graph
  layers_pre_mp: 0
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 64 # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: 'gelu'
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 1e-3
  max_epoch: 2000
  num_warmup_epochs: 50
#  scheduler: cosine_with_warmup
  scheduler: timm_cosine_with_warmup
  min_lr: 1e-5